In [1]:
import pandas as pd

In [2]:
# Job posting db
job_post = pd.read_csv('linkedin_job_postings.csv')

In [6]:
#export this to an excel file
# 2. Extract just the first 50 rows
sample_jp = job_post.head(50)

# 3. Export only the 50-row sample to Excel
sample_jp.to_excel('sample_job_postings_50.xlsx', index=False)

In [7]:
# Job skill db
job_skills = pd.read_csv('job_skills.csv')

In [8]:
#export this to an excel file 
# 2. Extract just the first 50 rows
sample_js = job_skills.head(50)

# 3. Export only the 50-row sample to Excel
sample_js.to_excel('sample_job_skills_50.xlsx', index=False)

In [8]:
job_skills

,job_link,job_skills
0,https://www.linkedin.com/jobs/view/housekeeper...,"Building Custodial Services, Cleaning, Janitor..."
1,https://www.linkedin.com/jobs/view/assistant-g...,"Customer service, Restaurant management, Food ..."
2,https://www.linkedin.com/jobs/view/school-base...,"Applied Behavior Analysis (ABA), Data analysis..."
3,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Engineering, Project Controls, Sche..."
4,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Assembly, Point to point wiring, St..."
...,...,...
1296376,https://www.linkedin.com/jobs/view/community-a...,"Communication Skills, Time Management, Custome..."
1296377,https://www.linkedin.com/jobs/view/sr-it-analy...,"Windows SQL, EDI X12, Edifecs Platform, Health..."
1296378,https://www.linkedin.com/jobs/view/operations-...,"Adaptability, Communication, Digital Fluency, ..."
1296379,https://www.linkedin.com/jobs/view/float-patie...,"CNA, EMT, BLS, Medical Assistant, CPCT, LPN, R..."
1296380,https://www.linkedin.com/jobs/view/conductor-e...,"Customer Service, Driving, Loading, Unloading,..."

In [9]:
job_post

,job_link,last_processed_time,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/account-exe...,2024-01-21 07:12:29.00256+00,t,t,f,Account Executive - Dispensing (NorCal/Norther...,BD,"San Diego, CA",2024-01-15,Coronado,United States,Color Maker,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/registered-...,2024-01-21 07:39:58.88137+00,t,t,f,Registered Nurse - RN Care Manager,Trinity Health MI,"Norton Shores, MI",2024-01-14,Grand Haven,United States,Director Nursing Service,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/restaurant-...,2024-01-21 07:40:00.251126+00,t,t,f,RESTAURANT SUPERVISOR - THE FORKLIFT,Wasatch Adaptive Sports,"Sandy, UT",2024-01-14,Tooele,United States,Stand-In,Mid senior,Onsite
3,https://www.linkedin.com/jobs/view/independent...,2024-01-21 07:40:00.308133+00,t,t,f,Independent Real Estate Agent,Howard Hanna | Rand Realty,"Englewood Cliffs, NJ",2024-01-16,Pinehurst,United States,Real-Estate Clerk,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/group-unit-...,2024-01-19 09:45:09.215838+00,f,f,f,Group/Unit Supervisor (Systems Support Manager...,"IRS, Office of Chief Counsel","Chamblee, GA",2024-01-17,Gadsden,United States,Supervisor Travel-Information Center,Mid senior,Onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1348449,https://www.linkedin.com/jobs/view/registered-...,2024-01-20 15:21:07.786118+00,t,t,f,Registered Nurse (RN) #CP-RN-7998660 - 2411627...,TravelNurseSource,"Providence, RI",2024-01-14,Fall River,United States,Nurse Supervisor,Mid senior,Onsite
1348450,https://www.linkedin.com/jobs/view/constructio...,2024-01-20 15:21:10.885264+00,t,t,f,Construction Superintendent,Jobot,"New Iberia, LA",2024-01-15,Lafayette,United States,Assistant Construction Superintendent,Mid senior,Onsite
1348451,https://www.linkedin.com/jobs/view/executive-c...,2024-01-21 07:40:00.304641+00,t,t,f,"Executive Chef, Operations Support",NEXDINE Hospitality,"Riverhead, NY",2024-01-14,Eastport,United States,Chef,Mid senior,Onsite
1348452,https://www.linkedin.com/jobs/view/rn-register...,2024-01-21 00:38:39.816821+00,t,t,f,"RN- Registered Nurse, Analyst - - 23934913EXPP...",TravelNurseSource,"Aurora, CO",2024-01-16,Colorado,United States,Occupational Analyst,Mid senior,Onsite
1348453,https://www.linkedin.com/jobs/view/on-demand-g...,2024-01-21 00:38:44.231492+00,t,t,f,"On-Demand: Guest Advocate (Cashier), General M...",Target,"Culver City, CA",2024-01-12,Malibu,United States,Cashier Ii,Mid senior,Onsite

In [9]:
#job sums again but import 1.3mil rows (similiar to the rows of the other 2 db)
job_sum = pd.read_csv('job_summary.csv',nrows=1348454)

In [10]:
#export this to an excel file 
# 2. Extract just the first 50 rows
sample_jsum = job_sum.head(50)

# 3. Export only the 50-row sample to Excel
sample_jsum.to_excel('sample_job_summary_50.xlsx', index=False)

In [13]:
job_sum

,job_link,job_summary
0,https://www.linkedin.com/jobs/view/restaurant-...,Rock N Roll Sushi is hiring a Restaurant Manag...
1,https://www.linkedin.com/jobs/view/med-surg-re...,Schedule\n: PRN is required minimum 12 hours p...
2,https://www.linkedin.com/jobs/view/registered-...,Description\nIntroduction\nAre you looking for...
3,https://uk.linkedin.com/jobs/view/commercial-a...,Commercial account executive\nSheffield\nFull ...
4,https://www.linkedin.com/jobs/view/store-manag...,Address:\nUSA-CT-Newington-44 Fenn Road\nStore...
...,...,...
1297327,https://www.linkedin.com/jobs/view/roofing-sup...,We are currently seeking experienced commercia...
1297328,https://www.linkedin.com/jobs/view/service-cen...,Overview\nStable and growing organization\nCom...
1297329,https://www.linkedin.com/jobs/view/flight-qual...,Rôle et responsabilités\nJob Description:\nFli...
1297330,https://www.linkedin.com/jobs/view/global-sour...,Job Description\nAre You Ready to Make It Happ...
1297331,https://www.linkedin.com/jobs/view/research-as...,Current Employees:\nIf you are a current Staff...

In [11]:
job_skills

,job_link,job_skills
0,https://www.linkedin.com/jobs/view/housekeeper...,"Building Custodial Services, Cleaning, Janitor..."
1,https://www.linkedin.com/jobs/view/assistant-g...,"Customer service, Restaurant management, Food ..."
2,https://www.linkedin.com/jobs/view/school-base...,"Applied Behavior Analysis (ABA), Data analysis..."
3,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Engineering, Project Controls, Sche..."
4,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Assembly, Point to point wiring, St..."
...,...,...
1296376,https://www.linkedin.com/jobs/view/community-a...,"Communication Skills, Time Management, Custome..."
1296377,https://www.linkedin.com/jobs/view/sr-it-analy...,"Windows SQL, EDI X12, Edifecs Platform, Health..."
1296378,https://www.linkedin.com/jobs/view/operations-...,"Adaptability, Communication, Digital Fluency, ..."
1296379,https://www.linkedin.com/jobs/view/float-patie...,"CNA, EMT, BLS, Medical Assistant, CPCT, LPN, R..."
1296380,https://www.linkedin.com/jobs/view/conductor-e...,"Customer Service, Driving, Loading, Unloading,..."

In [14]:
#Step 1: concat job skills and job postings
df = job_post.merge(job_skills, on="job_link", how="left")

In [15]:
df.columns.tolist()

['job_link',
 'last_processed_time',
 'got_summary',
 'got_ner',
 'is_being_worked',
 'job_title',
 'company',
 'job_location',
 'first_seen',
 'search_city',
 'search_country',
 'search_position',
 'job_level',
 'job_type',
 'job_skills']

In [18]:
#keep the core columns for analysis
core_col = ['job_link','job_title','company',
 'job_location', 'job_level',
 'job_type','job_skills', 'first_seen']

df_study = df[core_col]

In [19]:
df_study

,job_link,job_title,company,job_location,job_level,job_type,job_skills,first_seen
0,https://www.linkedin.com/jobs/view/account-exe...,Account Executive - Dispensing (NorCal/Norther...,BD,"San Diego, CA",Mid senior,Onsite,"Medical equipment sales, Key competitors, Term...",2024-01-15
1,https://www.linkedin.com/jobs/view/registered-...,Registered Nurse - RN Care Manager,Trinity Health MI,"Norton Shores, MI",Mid senior,Onsite,"Nursing, Bachelor of Science in Nursing, Maste...",2024-01-14
2,https://www.linkedin.com/jobs/view/restaurant-...,RESTAURANT SUPERVISOR - THE FORKLIFT,Wasatch Adaptive Sports,"Sandy, UT",Mid senior,Onsite,"Restaurant Operations Management, Inventory Ma...",2024-01-14
3,https://www.linkedin.com/jobs/view/independent...,Independent Real Estate Agent,Howard Hanna | Rand Realty,"Englewood Cliffs, NJ",Mid senior,Onsite,"Real Estate, Customer Service, Sales, Negotiat...",2024-01-16
4,https://www.linkedin.com/jobs/view/group-unit-...,Group/Unit Supervisor (Systems Support Manager...,"IRS, Office of Chief Counsel","Chamblee, GA",Mid senior,Onsite,NaN,2024-01-17
...,...,...,...,...,...,...,...,...
1348449,https://www.linkedin.com/jobs/view/registered-...,Registered Nurse (RN) #CP-RN-7998660 - 2411627...,TravelNurseSource,"Providence, RI",Mid senior,Onsite,"Registered Nurse, BLS certification, Nursing c...",2024-01-14
1348450,https://www.linkedin.com/jobs/view/constructio...,Construction Superintendent,Jobot,"New Iberia, LA",Mid senior,Onsite,"Construction management, Project planning, Est...",2024-01-15
1348451,https://www.linkedin.com/jobs/view/executive-c...,"Executive Chef, Operations Support",NEXDINE Hospitality,"Riverhead, NY",Mid senior,Onsite,"Culinary, Chef Director, Menu writing, Cycle o...",2024-01-14
1348452,https://www.linkedin.com/jobs/view/rn-register...,"RN- Registered Nurse, Analyst - - 23934913EXPP...",TravelNurseSource,"Aurora, CO",Mid senior,Onsite,"Registered Nurse, Analyst, RN Registered Nurse...",2024-01-16
1348453,https://www.linkedin.com/jobs/view/on-demand-g...,"On-Demand: Guest Advocate (Cashier), General M...",Target,"Culver City, CA",Mid senior,Onsite,"Customer service, Communication, Problem solvi...",2024-01-12

In [21]:
#Step 3: check for missing value
df_study.isna().sum()

job_link            0
job_title           0
company            11
job_location       19
job_level           0
job_type            0
job_skills      54158
first_seen          0
dtype: int64

In [26]:
job_post

,job_link,last_processed_time,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/account-exe...,2024-01-21 07:12:29.00256+00,t,t,f,Account Executive - Dispensing (NorCal/Norther...,BD,"San Diego, CA",2024-01-15,Coronado,United States,Color Maker,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/registered-...,2024-01-21 07:39:58.88137+00,t,t,f,Registered Nurse - RN Care Manager,Trinity Health MI,"Norton Shores, MI",2024-01-14,Grand Haven,United States,Director Nursing Service,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/restaurant-...,2024-01-21 07:40:00.251126+00,t,t,f,RESTAURANT SUPERVISOR - THE FORKLIFT,Wasatch Adaptive Sports,"Sandy, UT",2024-01-14,Tooele,United States,Stand-In,Mid senior,Onsite
3,https://www.linkedin.com/jobs/view/independent...,2024-01-21 07:40:00.308133+00,t,t,f,Independent Real Estate Agent,Howard Hanna | Rand Realty,"Englewood Cliffs, NJ",2024-01-16,Pinehurst,United States,Real-Estate Clerk,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/group-unit-...,2024-01-19 09:45:09.215838+00,f,f,f,Group/Unit Supervisor (Systems Support Manager...,"IRS, Office of Chief Counsel","Chamblee, GA",2024-01-17,Gadsden,United States,Supervisor Travel-Information Center,Mid senior,Onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1348449,https://www.linkedin.com/jobs/view/registered-...,2024-01-20 15:21:07.786118+00,t,t,f,Registered Nurse (RN) #CP-RN-7998660 - 2411627...,TravelNurseSource,"Providence, RI",2024-01-14,Fall River,United States,Nurse Supervisor,Mid senior,Onsite
1348450,https://www.linkedin.com/jobs/view/constructio...,2024-01-20 15:21:10.885264+00,t,t,f,Construction Superintendent,Jobot,"New Iberia, LA",2024-01-15,Lafayette,United States,Assistant Construction Superintendent,Mid senior,Onsite
1348451,https://www.linkedin.com/jobs/view/executive-c...,2024-01-21 07:40:00.304641+00,t,t,f,"Executive Chef, Operations Support",NEXDINE Hospitality,"Riverhead, NY",2024-01-14,Eastport,United States,Chef,Mid senior,Onsite
1348452,https://www.linkedin.com/jobs/view/rn-register...,2024-01-21 00:38:39.816821+00,t,t,f,"RN- Registered Nurse, Analyst - - 23934913EXPP...",TravelNurseSource,"Aurora, CO",2024-01-16,Colorado,United States,Occupational Analyst,Mid senior,Onsite
1348453,https://www.linkedin.com/jobs/view/on-demand-g...,2024-01-21 00:38:44.231492+00,t,t,f,"On-Demand: Guest Advocate (Cashier), General M...",Target,"Culver City, CA",2024-01-12,Malibu,United States,Cashier Ii,Mid senior,Onsite

In [29]:
df_study["job_link"].duplicated().sum()

np.int64(0)

In [30]:
#convert value in job_title column to start filter out all cell contain "business analyst"
df_study["job_title"] = (df_study["job_title"].str.lower().str.strip())

In [31]:
df_study

,job_link,job_title,company,job_location,job_level,job_type,job_skills,first_seen
0,https://www.linkedin.com/jobs/view/account-exe...,account executive - dispensing (norcal/norther...,BD,"San Diego, CA",Mid senior,Onsite,"Medical equipment sales, Key competitors, Term...",2024-01-15
1,https://www.linkedin.com/jobs/view/registered-...,registered nurse - rn care manager,Trinity Health MI,"Norton Shores, MI",Mid senior,Onsite,"Nursing, Bachelor of Science in Nursing, Maste...",2024-01-14
2,https://www.linkedin.com/jobs/view/restaurant-...,restaurant supervisor - the forklift,Wasatch Adaptive Sports,"Sandy, UT",Mid senior,Onsite,"Restaurant Operations Management, Inventory Ma...",2024-01-14
3,https://www.linkedin.com/jobs/view/independent...,independent real estate agent,Howard Hanna | Rand Realty,"Englewood Cliffs, NJ",Mid senior,Onsite,"Real Estate, Customer Service, Sales, Negotiat...",2024-01-16
4,https://www.linkedin.com/jobs/view/group-unit-...,group/unit supervisor (systems support manager...,"IRS, Office of Chief Counsel","Chamblee, GA",Mid senior,Onsite,NaN,2024-01-17
...,...,...,...,...,...,...,...,...
1348449,https://www.linkedin.com/jobs/view/registered-...,registered nurse (rn) #cp-rn-7998660 - 2411627...,TravelNurseSource,"Providence, RI",Mid senior,Onsite,"Registered Nurse, BLS certification, Nursing c...",2024-01-14
1348450,https://www.linkedin.com/jobs/view/constructio...,construction superintendent,Jobot,"New Iberia, LA",Mid senior,Onsite,"Construction management, Project planning, Est...",2024-01-15
1348451,https://www.linkedin.com/jobs/view/executive-c...,"executive chef, operations support",NEXDINE Hospitality,"Riverhead, NY",Mid senior,Onsite,"Culinary, Chef Director, Menu writing, Cycle o...",2024-01-14
1348452,https://www.linkedin.com/jobs/view/rn-register...,"rn- registered nurse, analyst - - 23934913expp...",TravelNurseSource,"Aurora, CO",Mid senior,Onsite,"Registered Nurse, Analyst, RN Registered Nurse...",2024-01-16
1348453,https://www.linkedin.com/jobs/view/on-demand-g...,"on-demand: guest advocate (cashier), general m...",Target,"Culver City, CA",Mid senior,Onsite,"Customer service, Communication, Problem solvi...",2024-01-12

In [32]:
df_study[df_study["job_title"].str.contains("business analyst", na=False)]["job_title"].value_counts()

job_title
business analyst                                                                                                1024
senior business analyst                                                                                          214
jde business analyst (supply chain)                                                                              163
jd edwards business analyst                                                                                      150
it business analyst                                                                                               67
                                                                                                                ...
business analyst - nav/business central - sacramento - $120k                                                       1
business analyst/scrum master - need local candidates                                                              1
business analyst, sr.                                                                                              1
payments business analyst                                                                                          1
senior business analyst, salesforce, chief operating officer/strategic operations and performance management       1
Name: count, Length: 2007, dtype: int64

In [33]:
df_study[df_study["job_title"].str.contains("business analyst", na=False)]["job_title"]

343                          secret cleared business analyst
401                               business analyst (11076-1)
530                       payment (swift) (business analyst)
797                               principal business analyst
1258                                        business analyst
                                 ...
1346654                            payments business analyst
1346865                             pgd sr. business analyst
1346983                                 business analyst - b
1347733    senior business analyst, salesforce, chief ope...
1347772                  jde business analyst (supply chain)
Name: job_title, Length: 4576, dtype: str

In [34]:
df_study[df_study["job_title"].str.contains("business analyst", na=False)]["job_title"].nunique()

2007

In [35]:
df_study[df_study["job_title"].str.contains("business analysis", na=False)]["job_title"].value_counts()

job_title
business analysis and integration analyst                    5
technical consultant - business analysis                     4
manager, business analysis, spectrum enterprise              3
business analysis                                            2
senior analyst it business analysis-hybrid                   2
                                                            ..
business analysis manager - vice president                   1
business analysis manager - vp - public sector operations    1
business analysis, senior analyst (installation support)     1
business analysis/ ms dynamics d365                          1
manager business analysis                                    1
Name: count, Length: 70, dtype: int64

In [36]:
df_study[df_study["job_title"].str.contains("business analysis", na=False)]["job_title"].nunique()

70

In [37]:
#filter out the records contain "business analyst"
ba_df = df_study[df_study["job_title"].str.contains("business analyst", na=False)]

In [38]:
ba_df.isna().sum()

job_link          0
job_title         0
company           0
job_location      0
job_level         0
job_type          0
job_skills      136
first_seen        0
dtype: int64

In [40]:
#see how many records are there
len(ba_df)

4576

In [41]:

ba_df["job_level"].value_counts()

job_level
Mid senior    4057
Associate      519
Name: count, dtype: int64

In [44]:
ba_df["job_location"].value_counts()

job_location
New York, NY                       105
Boston, MA                          86
Atlanta, GA                         85
Chicago, IL                         68
London, England, United Kingdom     67
                                  ...
Wildwood, MO                         1
Evanston, IL                         1
Costa Mesa, CA                       1
Lucknow, Victoria, Australia         1
Clifton Forge, VA                    1
Name: count, Length: 1095, dtype: int64

In [45]:
location_parts = ba_df["job_location"].str.split(",").str.len()

location_parts.value_counts().sort_index()

job_location
1      75
2    3703
3     798
Name: count, dtype: int64

In [46]:
ba_df[location_parts == 1]["job_location"].value_counts()

job_location
United States                           15
New York City Metropolitan Area          8
Oklahoma City Metropolitan Area          5
Utica-Rome Area                          5
Greater Sydney Area                      4
Los Angeles Metropolitan Area            3
Greater Phoenix Area                     2
Greater Cleveland                        2
Greater Syracuse-Auburn Area             2
Greater Reno Area                        2
Greater Minneapolis-St. Paul Area        2
Washington DC-Baltimore Area             1
Greater Orlando                          1
Buffalo-Niagara Falls Area               1
Greater Philadelphia                     1
Mexico City Metropolitan Area            1
Greater Macon                            1
Tallahassee Metropolitan Area            1
Greater Anchorage Area                   1
Greater Melbourne Area                   1
Kansas City Metropolitan Area            1
Nashville Metropolitan Area              1
Cincinnati Metropolitan Area             1
Worcester and Kidderminster Area         1
Charlotte Metro                          1
San Francisco Bay Area                   1
Greater Tampa Bay Area                   1
Greater Ottawa Metropolitan Area         1
Miami-Fort Lauderdale Area               1
Dallas-Fort Worth Metroplex              1
Greater St. John's Metropolitan Area     1
Brownsville Metropolitan Area            1
Greater Brisbane Area                    1
Atlanta Metropolitan Area                1
Greater Boston                           1
Canada                                   1
Name: count, dtype: int64

In [47]:
ba_df[location_parts == 2]["job_location"].value_counts()

job_location
New York, NY         105
Boston, MA            86
Atlanta, GA           85
Chicago, IL           68
Dallas, TX            58
                    ...
Bismarck, ND           1
Wildwood, MO           1
Evanston, IL           1
Costa Mesa, CA         1
Clifton Forge, VA      1
Name: count, Length: 845, dtype: int64

In [48]:
ba_df[location_parts == 3]["job_location"].value_counts()

job_location
London, England, United Kingdom             67
Sydney, New South Wales, Australia          49
Toronto, Ontario, Canada                    47
Montreal, Quebec, Canada                    45
Melbourne, Victoria, Australia              42
                                            ..
North Sydney, New South Wales, Australia     1
Rockingham, Western Australia, Australia     1
Mexicali, Baja California, Mexico            1
Leicestershire, England, United Kingdom      1
Lucknow, Victoria, Australia                 1
Name: count, Length: 214, dtype: int64

In [49]:
ba_df["job_type"].value_counts()

job_type
Onsite    4574
Remote       1
Hybrid       1
Name: count, dtype: int64

In [50]:
df_study["job_type"].value_counts()

job_type
Onsite    1337633
Hybrid       6562
Remote       4259
Name: count, dtype: int64

In [51]:
ba_df["company"].value_counts().head(20)

company
LATICRETE International                              312
Dice                                                 168
Tata Consultancy Services                             71
Stellent IT                                           59
NR Consulting                                         58
Jobs for Humanity                                     44
Robert Half                                           41
Software Technology Inc.                              40
Diverse Lynx                                          38
Steneral Consulting                                   29
CERES Group                                           28
TekIntegral                                           28
HireTalent - Diversity Staffing & Recruiting Firm     26
Intellectt Inc                                        26
Capital One                                           25
ClearanceJobs                                         24
EY                                                    22
Capleo Global                                         22
Extend Information Systems Inc.                       22
Agoda                                                 22
Name: count, dtype: int64

In [55]:
ba_df["job_skills"].dropna()

343        Microsoft Office 365, Microsoft Teams, SharePo...
401        Technical Writing, Information Security, Micro...
797        NEER, FPL, Reliability reporting, GADS applica...
1271       Business Analysis, Business Requirements Gathe...
1525       Pricing Transparency Analyst, Data analysis, Q...
                                 ...
1346654    Payments messages (Fedwire Swift), Canonical d...
1346865    Microsoft Excel, Powerpoint, SAP, Power BI, Bu...
1346983    Business Analyst, Business Systems Analysis, S...
1347733    Salesforce, Data Analysis, Data Interpretation...
1347772    JDE E1, ERP Implementation, Manufacturing, Sup...
Name: job_skills, Length: 4440, dtype: str

In [58]:
skill_count = ba_df["job_skills"].str.split(",")

skill_count

343        [Microsoft Office 365,  Microsoft Teams,  Shar...
401        [Technical Writing,  Information Security,  Mi...
530                                                      NaN
797        [NEER,  FPL,  Reliability reporting,  GADS app...
1258                                                     NaN
                                 ...
1346654    [Payments messages (Fedwire Swift),  Canonical...
1346865    [Microsoft Excel,  Powerpoint,  SAP,  Power BI...
1346983    [Business Analyst,  Business Systems Analysis,...
1347733    [Salesforce,  Data Analysis,  Data Interpretat...
1347772    [JDE E1,  ERP Implementation,  Manufacturing, ...
Name: job_skills, Length: 4576, dtype: object

In [79]:
#view how it look
skill_count.iloc[1]

['Technical Writing',
 ' Information Security',
 ' Microsoft Office Suite',
 ' Project Management',
 ' POAM Processes',
 ' CMS Regulation Compliance',
 ' Business Analysis',
 ' Communication Skills',
 ' Information Technology',
 ' Visual Aids',
 ' Presentations',
 ' Teamwork',
 ' Multitasking',
 ' Prioritization',
 ' Attention to Detail',
 ' Complex Processes',
 ' Strong English Language Skills',
 ' Grammar',
 ' Constructive Criticism',
 ' System Security Plans',
 ' Advance Planning Documents',
 ' Request For Proposals',
 ' CMS MARSE 2.2',
 ' NIST Risk Management Framework (RMF)',
 ' Bizagi',
 ' Public Sector Work Experience',
 ' eGRC Tool',
 " Bachelor's Degree in English Journalism or Technical Writing"]

In [68]:
skill_df = (
    ba_df[["job_title", "job_skills"]]
    .dropna(subset=["job_skills"])
    .copy()
)

skill_df["job_skills"] = skill_df["job_skills"].str.split(",")

skill_df = skill_df.explode("job_skills")

skill_df["job_skills"] = skill_df["job_skills"].str.strip().str.lower()

In [69]:
skill_df

                                   job_title            job_skills
343          secret cleared business analyst  microsoft office 365
343          secret cleared business analyst       microsoft teams
343          secret cleared business analyst     sharepoint online
343          secret cleared business analyst  sharepoint 2016/2019
343          secret cleared business analyst  microsoft powerpoint
...                                      ...                   ...
1347772  jde business analyst (supply chain)      flexible mindset
1347772  jde business analyst (supply chain)          adaptability
1347772  jde business analyst (supply chain)    hybrid/remote work
1347772  jde business analyst (supply chain)        extended hours
1347772  jde business analyst (supply chain)      us est time zone

[111053 rows x 2 columns]

In [78]:
skill_df["job_skills"].value_counts().head(20)

job_skills
business analysis         1956
project management        1544
data analysis             1473
communication             1369
sql                       1055
analytical skills          906
requirements gathering     779
problem solving            774
communication skills       742
teamwork                   666
agile                      659
business analyst           547
problemsolving             475
stakeholder management     473
documentation              471
collaboration              471
jira                       449
excel                      446
attention to detail        413
bachelor's degree          412
Name: count, dtype: int64